# Generated by Django 5.0.6 on 2024-05-11 14:28

from django.db import migrations

def load_initial_data(apps, schema_editor):
    Character = apps.get_model('api', 'Character')
    Character.objects.create(name='Yoda', origin='Star Wars')
    Character.objects.create(name='Donald Trump')
    Character.objects.create(name='Gollum', origin='The Lord of the Rings)')
    Character.objects.create(name='Hodor', origin='Game of Thrones)')
    Character.objects.create(name='Minions', origin='Despicable Me')
    Character.objects.create(name='Tarzan')

def unload_initial_data(apps, schema_editor):
    Character = apps.get_model('api', 'Character')
    Character.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, unload_initial_data),
    ]
