name: Django CI

on:
  push:
    paths:
      - 'webservice/**'
      - '.github/workflows/django.yml'

defaults:
  run:
    working-directory: webservice

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.12 ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: poetry install

      - name: Run Django migrations
        run: python manage.py migrate

      - name: Run Django tests
        run: python manage.py test
