name: Django CI

on:
  push:
    paths:
      - 'webservice/**'
      - '.github/workflows/django.yml'

defaults:
  run:
    working-directory: webservice

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python and Poetry
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          source $HOME/.poetry/env

      - name: Install dependencies with Poetry
        run: poetry install

      - name: Run Django migrations
        run: poetry run python manage.py migrate

      - name: Run Django tests
        run: poetry run python manage.py test
